Setup the skeleton for the CXL plugin
conversionxl/woocommerce-subscriptions-api-export pull request #1
Opened 2020-12-28 20:53 UTC by umeshghediya

Setup Basic skeleton for the WP CLI command

2020-12-31 12:12 UTC, lkraav requested changes

2020-12-31 12:12 UTC, lkraav commented on Commands/class-cxl-cli.php
> +class CLX_CLI extends WP_CLI_Command {
CXL, not CLX.

2020-12-31 12:12 UTC, lkraav commented on Commands/class-cxl-cli.php
> +<?php
Everything must be namespaced.

2020-12-31 12:12 UTC, lkraav commented on cxl-wp-cli-commands.php
> +function cxl_autoloader( $class ) {
Let's use composer autoloader.

2020-12-31 12:12 UTC, lkraav commented on cxl-wp-cli-commands.php
> + * Version:           1.0.0
0.1.0 makes more sense to start.

2021-01-03 19:41 UTC, umeshghediya commented on Commands/class-cxl-cli.php
> +<?php
Done

2021-01-03 19:41 UTC, umeshghediya commented on cxl-wp-cli-commands.php
> + * Version:           1.0.0
Done

2021-01-03 19:42 UTC, umeshghediya commented on cxl-wp-cli-commands.php
> +function cxl_autoloader( $class ) {
Okay sure, but can we keep this, for now, once cleared with other PRs we'll change this one, as currently needs to change in 7 more PRs.

2021-01-04 08:57 UTC, lkraav commented on cxl-wp-cli-commands.php
> -if ( ! class_exists( 'WP_CLI' ) ) {
What is this line change about?

2021-01-04 09:24 UTC, umeshghediya commented on cxl-wp-cli-commands.php
> -if ( ! class_exists( 'WP_CLI' ) ) {
Space was added by mistake.

2021-01-08 14:53 UTC, merged