Phase 1 - Integrate ChartMogul into WP/WooCommerce
conversionxl/woocommerce-subscriptions-api-export pull request #26
Opened 2021-06-22 10:27 UTC by saas786

- Report revenue and churn metrics accurately from WooCommerce Data.

### Phase 1: Develop WP-CLI integration with ChartMogul to import historical WooCommerce data.

 - Re-evaluate primary method of targeting WooCommerce Data (Pulling from Subscriptions vs Orders) Ensure non-recurring revenue products are tracked properly
 - Develop chartmogul functions into reusable class, want to reuse as much code for phase 2 and 3 implementations.
 - Develop data types for validation before sending to ChartMogul functions
 - Ensure proper implementation of importing trial starts and conversions.
 - Ensure trialers who aren't converted are still considered leads in ChartMogul .
 - Refactor functions to follow common sequence patterns from ChartMogul , configurable by function arguments.

 - fix issue https://github.com/conversionxl/woocommerce-subscriptions-api-export/issues/18
 - fix issue https://github.com/conversionxl/woocommerce-subscriptions-api-export/issues/16
 - fix issue https://github.com/conversionxl/woocommerce-subscriptions-api-export/issues/19
 - fix issue https://github.com/conversionxl/woocommerce-subscriptions-api-export/issues/25
 - fix issue https://github.com/conversionxl/woocommerce-subscriptions-api-export/issues/23
 - fix issue https://github.com/conversionxl/woocommerce-subscriptions-api-export/issues/22
 - fix issue https://github.com/conversionxl/woocommerce-subscriptions-api-export/issues/20
 - fix issue https://github.com/conversionxl/woocommerce-subscriptions-api-export/issues/17
 - fix issue https://github.com/conversionxl/woocommerce-subscriptions-api-export/issues/15
 - fix issue https://github.com/conversionxl/woocommerce-subscriptions-api-export/issues/14
 - Rename namespace
 - integrated PR #12
 - only process completed / failed / refunded orders
 - add membership attributes to customer
 - conditionally create invoice, customer, plans etc
 - setup lead & trial logic
 - allow customer update as well
 - add subscription cancelled feature
 - add refunds
 - fetch all orders
 - add memberships as tags
 - accept params via url
 - bump composer packages & update composer.lock file

2021-06-22 15:00 UTC, pawelkmpt commented on src/ChartMogul/Component.php
> +			->setSecretKey( '7bc86adc87d56a6371d11014ba0a9ad5' );
these should not be committed ⚠️ 
use WP options to store these values

2021-06-22 15:14 UTC, saas786 commented on src/ChartMogul/Component.php
> +			->setSecretKey( '7bc86adc87d56a6371d11014ba0a9ad5' );
> 
> 
> these should not be committed ⚠️
> use WP options to store these values
Missed it, will fix.

2021-06-22 15:33 UTC, saas786 commented on src/ChartMogul/Component.php
> +			->setSecretKey( '7bc86adc87d56a6371d11014ba0a9ad5' );
> > these should not be committed ⚠️
> > use WP options to store these values
> > Missed it, will fix.

Done removed

2021-06-23 09:17 UTC, pawelkmpt commented
@saas786 I'm reviewing the code. It won't be easy because you made one huge commit, so can't look at the process step by step.

After general look I have a feeling you over-engineered it. It's unlikely we'll simplify it now (it would be waste of time) but I doubt we need any proxies for few (?) WP-CLI commands.

I also see textdomain loaded. Was it a requirement? In general we don't use translations as all content is in english anyway, so including such functionalities is also waste of time and maybe a bit of performance hit.

Alright, I'm getting deeper into code and will provide more detailed feedback on specific parts.

2021-06-23 09:39 UTC, saas786 commented
> @saas786 I'm reviewing the code. It won't be easy because you made one huge commit, so can't look at the process step by step.
> 
> After general look I have a feeling you over-engineered it. It's unlikely we'll simplify it now (it would be waste of time) but I doubt we need any proxies for few (?) WP-CLI commands.
> 
> I also see textdomain loaded. Was it a requirement? In general we don't use translations as all content is in english anyway, so including such functionalities is also waste of time and maybe a bit of performance hit.
> 
> Alright, I'm getting deeper into code and will provide more detailed feedback on specific parts.

- It was multiple commits, usually you ask for fewer commits, so squashed it into single commit.
- Ignore the `/Proxies, /Core, /Tools` as are just aid / helpers.
- Its no longer few WP CLI commands, it will now integrate with AutomateWoo, for testing on live, as no wp cli access is possible, create Query Params component to initial it via URLs...
- Can remove lang stuff if needed.

a) There are multiple entry points **src/CLI**, **src/Query** and now **src/AutomateWoo** (not implemented yet)
b) Split packages **src/ChartMogul**, **src/WC**, **src/WP**
c) Main package **/src/Export**

Hopefully its clear now.

2021-06-23 10:44 UTC, pawelkmpt commented
@saas786 can you explain me the idea behind using Monolog and `Logger::log()` instead of native `WP_CLI` logging methods?

2021-06-23 12:54 UTC, pawelkmpt commented
**`src/Plugin.php` vs `bootstrap-plugin.php`**

When unnecessary code is removed from `src/Plugin.php` it will basically just include `bootstrap-plugin.php`. So I'm wondering if we can do one of these things:
* drop `src/Plugin.php` and bootstrap everything in `bootstrap-plugin.php`,
* copy content of `bootstrap-plugin.php` to `Plugin::init()` instead of including the file.

For me having `Plugin` and `bootstrap-plugin` is confusing at the first glance, because it's not clear which file is actually bootstrapping the plugin.

2021-06-23 12:59 UTC, pawelkmpt requested changes

2021-06-23 12:59 UTC, pawelkmpt commented on src/Export/Component.php
> +	private bool $has_trial = false;
I think these should be set for customer (object), not globally for command class.

2021-06-23 12:59 UTC, pawelkmpt commented on src/WC/Subscriptions.php
> +	public static function getSubscriptionForOrder( $order, array $args = [] ): ?WC_Subscription {
Second param is never used.

2021-06-23 12:59 UTC, pawelkmpt commented on src/WC/Subscriptions.php
> +	 *            'order_type' Get subscriptions for the any order type in this array. Can include 'any', 'parent', 'renewal' or 'switch', defaults to parent.
I don't see the reason to copy docs of `wcs_get_subscriptions_for_order()`. Just add `@see wcs_get_subscriptions_for_order()` and jump the the origin

2021-06-23 12:59 UTC, pawelkmpt commented on src/Export/Component.php
> +				Logger::log()->info( 'Subscription cancelled.' );
I think this part could be separate method

2021-06-23 12:59 UTC, pawelkmpt commented on .eslintignore
> +webpack.mix.export.js
we don't have any JS and I doubt we will need. this file is unnecessary

2021-06-23 12:59 UTC, pawelkmpt commented on .eslintrc.js
> +module.exports = require('@conversionxl/lint-staged-config/.eslintrc.js');
we don't have any JS and I doubt we will need. this file is unnecessary

2021-06-23 12:59 UTC, pawelkmpt commented on .stylelintignore
> +public
we don't have any CSS and I doubt we will need. this file is unnecessary

2021-06-23 12:59 UTC, pawelkmpt commented on .stylelintrc
> +}
we don't have any CSS and I doubt we will need. this file is unnecessary

2021-06-23 12:59 UTC, pawelkmpt commented on changelog.md
> +# Change Log
I don't think changelog is necessary

2021-06-23 12:59 UTC, pawelkmpt commented on license.md
> +(c) Copyright 2021 ConversionXL LLC, all rights reserved.
delete it

2021-06-23 12:59 UTC, pawelkmpt commented on package.json
> +  }
lots of stuff related to css and js. we don't have these. remove what's not needed

2021-06-23 12:59 UTC, pawelkmpt commented on plugin.php
>   * Version: 0.1.0
put date in format 2021.06.23 as version

2021-06-23 12:59 UTC, pawelkmpt commented on src/Export/Component.php
> +		$subscription = WCSubscriptions::getSubscriptionForOrder( $order->get_id() );
sanity check needed

2021-06-23 12:59 UTC, pawelkmpt commented on src/Export/Component.php
> +<?php
Lots of methods is missing typing and comments.
Please skip `@param` phpdocs though when params are typed. No need to repeat the info

2021-06-23 12:59 UTC, pawelkmpt commented on src/Query/Component.php
> +<?php
Why do we need this class?

2021-06-23 12:59 UTC, pawelkmpt commented on src/WC/Memberships.php
> + * @inheritDoc
inherit from where?

2021-06-23 12:59 UTC, pawelkmpt commented on webpack.mix.export.js
> +/**
I don't think we need build magic. No JS, no CSS, just plain PHP and plugin working with just `composer i`

2021-06-23 13:04 UTC, pawelkmpt commented
> * It was multiple commits, usually you ask for fewer commits, so squashed it into single commit.

I don't remember asking about fewer commits. @lkraav and me usually want smaller pieces of code more often than big chunk of code.

> * Ignore the `/Proxies, /Core, /Tools` as are just aid / helpers.
> * Its no longer few WP CLI commands, it will now integrate with AutomateWoo, for testing on live, as no wp cli access is possible, create Query Params component to initial it via URLs...

was query params init a requirement? cc @tomasced 

> * Can remove lang stuff if needed.

yes, please remove. I don't see a reason for using it.

> a) There are multiple entry points **src/CLI**, **src/Query** and now **src/AutomateWoo** (not implemented yet)
> b) Split packages **src/ChartMogul**, **src/WC**, **src/WP**
> c) Main package **/src/Export**

Quite complex. Also namespacing could be better: `WC -> WooCommerce`, `WP -> WordPress`, `CLI -> WPCLI`.
I think that acronyms are fine for functions to avoid long names but namespaces are better if they look natural.

Do not rename them now though. It can cause a mess in commits. We might decide on it later.

2021-06-24 14:23 UTC, saas786 commented
> @saas786 can you explain me the idea behind using Monolog and `Logger::log()` instead of native `WP_CLI` logging methods?

Logging is used in PHP side of things, not just only wp cli, if WP_CLI::log() etc helpers are used, it fails in none wp cli mode, specifically in AutomateWoo integration...

AutomateWoo also provides its on logger, so using Monolog makes it easy to use single interface and behind the scenes respective loggers are used.

2021-06-24 14:27 UTC, saas786 commented
> **`src/Plugin.php` vs `bootstrap-plugin.php`**
> 
> When unnecessary code is removed from `src/Plugin.php` it will basically just include `bootstrap-plugin.php`. So I'm wondering if we can do one of these things:
> 
> * drop `src/Plugin.php` and bootstrap everything in `bootstrap-plugin.php`,
> * copy content of `bootstrap-plugin.php` to `Plugin::init()` instead of including the file.
> 
> For me having `Plugin` and `bootstrap-plugin` is confusing at the first glance, because it's not clear which file is actually bootstrapping the plugin.

Idea was to provide singleton class to provide access to some plugin data, and bootstrap-plugin is just to bootstrap the app part, sure, can merge bootstrap-plugin into Plugin init.

2021-06-24 14:29 UTC, saas786 commented on plugin.php
> +
> It should have `if ( defined( 'WP_CLI' ) && WP_CLI ) {}` condition. It doesn't make sense to load anything if it's not WP-CLI request.

Plugin is not specific to WP CLI only, it has an interface for AutomateWoo.

2021-06-24 14:30 UTC, saas786 commented on src/Provider.php
> +		$this->cxl_wc_chartmogul->instance( 'cxl/wc/chartmogul/path', \CXL_WC_CHARTMOGUL_PLUGIN_DIR );
> It's basically making another copy of constant which is globally available. I don't see the point of such operation. Just use `CXL_WC_CHARTMOGUL_PLUGIN_DIR` constant when needed.
> 
> btw. is it necessary to prepend it with `\` ?

Will discard it. `\` was weirdly added by PHPCS, removed it on few occasions, but sometimes it got re-added.

2021-06-24 14:31 UTC, saas786 commented on src/Query/Component.php
> +<?php
> Why do we need this class?

It was added to test things on live website, because of no wp cli access for me or Tomas. So we can test it by passing params via Query Strings...

2021-06-24 14:32 UTC, saas786 commented on webpack.mix.export.js
> +/**
> I don't think we need build magic. No JS, no CSS, just plain PHP and plugin working with just `composer i`

It was added to support i18n, will remove.

2021-06-24 16:20 UTC, saas786 commented
@pawelkmpt Made the requested changes, please take a look.
Also let me know if I should squash the commits as well?

2021-07-02 06:18 UTC, pawelkmpt commented
> Logging is used in PHP side of things, not just only wp cli, if WP_CLI::log() etc helpers are used, it fails in none wp cli mode, specifically in AutomateWoo integration...
> 
> AutomateWoo also provides its on logger, so using Monolog makes it easy to use single interface and behind the scenes respective loggers are used.

this makes sense 👍

2021-07-02 06:37 UTC, pawelkmpt commented
> @pawelkmpt Made the requested changes, please take a look.

I see you made changes like formatting, code style, cleaning etc. but there's over 30 comments which appear after you click the button between the comments and I see none of them were attended.

> Also let me know if I should squash the commits as well?

Keep them

2021-07-02 10:19 UTC, saas786 commented
> I see you made changes like formatting, code style, cleaning etc. but there's over 30 comments which appear after you click the button between the comments and I see none of them were attended.

Formatting and linting changes are on top of your requested changes.

Please highlight which changes I have missed, as I have tried to be thorough and implement changes as requested.

2021-07-02 12:18 UTC, pawelkmpt commented
> Formatting and linting changes are on top of your requested changes.
> 
> Please highlight which changes I have missed, as I have tried to be thorough and implement changes as requested.

This is everything I see:

![Screenshot 2021-07-02 at 14 09 03](https://user-images.githubusercontent.com/5165721/124273103-e701a780-db3f-11eb-8d96-c7a03b23fb2d.png)
![Screenshot 2021-07-02 at 14 14 14](https://user-images.githubusercontent.com/5165721/124273109-e8cb6b00-db3f-11eb-909f-bae4cb71d5a5.png)
![Screenshot 2021-07-02 at 14 14 23](https://user-images.githubusercontent.com/5165721/124273112-e9640180-db3f-11eb-988d-bda572594bc4.png)


There's no commits about
* `src/CLI/Component.php`
* `src/ChartMogul/Component.php`
* `src/Tools/Logger/Component.php`
* `src/Export/Component.php`
* `README.md`
* ...

I won't list all files. Just check all comments and files.

2021-07-02 15:33 UTC, saas786 commented on src/ChartMogul/Component.php
> +	 * $ wp option add cxl_cm_account_token 900asdfasdc019adkjasdf09808
> command for adding option should have `--autoload=no` additionally.
> 
> btw. is this string a real token?

No, its dummy token.

2021-07-02 15:41 UTC, saas786 commented on src/ChartMogul/Component.php
> +		return null;
> I see `return null` in lots of places. Do we need to explicitly return `null`?

We either need actual object, otherwise null to easily compare it. If you feel at some places it can be avoid, please suggest.

2021-07-02 15:49 UTC, saas786 commented on src/Tools/Logger/Component.php
> +<?php
> > When the log root folder is inside WordPress content folder, the logs are going to be publicly accessible, and that is in best case a privacy leakage issue, in worst case a security threat.
> 
> what kind of sensitive data are we logging and why do we need to do it?

Basically, we are rendering / executing same code no matter the interface used here...
Like in WP CLI, we are rending same code, and it automatically uses WP CLI Logger, in none WP CLI mode, it seamlessly logs the errors etc, if we don't use Monolog, we will have to add platform specific conditions in code, to log errors.
If WC_Logger uses Monolog, certainly I could potentially use it, otherwise, my approach is friendly logging for each interface.

2021-07-02 15:53 UTC, saas786 commented on src/Export/Component.php
> +			}
> `WP_CLI::error()` exits the script automatically

Yes true, but only in WP CLI mode, in AutomateWoo or Query interface, it doesn't bail. So return is necessary.

2021-07-02 16:41 UTC, saas786 commented on src/Export/Component.php
> +	private function createCustomer( WC_Order $order ): object {
> This method does too many things. It should only create a customer and do additional actions separately.

Cleaned it in phase2 code, can re-check once this PR is merged and phase2 PR is filled.

2021-07-02 16:44 UTC, saas786 commented on src/WP/Component.php
> +	}
> I think this method (and class) is unnecessary. `get_user_by()` returns `WP_User|false` so it's easy to use in `if`.
> 
> It basically wrap the native WP function to return `null` instead of `false` when user does not exist.

As far as I remember, its same reason doing it like this, because of type hinting, and null logic. Ignore it for now, can revisit  later.

2021-07-02 16:47 UTC, saas786 commented on src/Export/Component.php
> +			$this->create_refund_invoice( $customer, $order, $refund_type );
> one class, different method naming styles. please be consistent.

Some changes are done in this PR, and further changes are done in phas2 branch, improving naming as I notice.

2021-07-02 16:48 UTC, saas786 commented on src/Export/Component.php
> +	private function add_cli_log( int $id, string $log_type = 'subscription' ): void {
> This method name in unclear. I'm confused now why do we need another logging method if we already have `Logger::log()` and possibility to use `WP_CLI::log()`

It certainly needs cleanup, it was there in initial code, didn't tackle it properly so far. Ignore it, will change the logic and might remove the function altogether.

2021-07-02 16:52 UTC, saas786 commented on src/Export/Component.php
> +	}
> Both of them do the same thing.

Correct, but this logic is to have separate calculations for normal order invoices vs refund invoices, currently both have same code, but might change, as we do further testing. Because refunds might have different totals (no taxes etc). But currently using `get_total_tax()` for both normal and refund totals, which might be incorrect logic.

2021-07-02 16:55 UTC, saas786 commented on README.md
> +    Success: Data source created successfully.
Good suggestion, I have same thinking, but avoided it, to minimize the refactor. Certainly going to circle back to it after this PR merge, possibly in phase2 PR.

Yep, your suggestions are appropriate.

Readme updated in phase2, will revisit once in phase2 review.

2021-07-02 17:04 UTC, saas786 commented
I see, apologies, I missed the hidden comments in scroll.

Implemented changes, please review and let me know.

2021-07-06 09:20 UTC, pawelkmpt commented on src/ChartMogul/Component.php
> +		return null;
I was just wondering what is the good practice:
* `return null` or
* `return` which also returns `null`.

2021-07-06 09:25 UTC, pawelkmpt commented
> I see, apologies, I missed the hidden comments in scroll.
> 
> Implemented changes, please review and let me know.

I see you fixed the most important things and also mentioned multiple times about phase 2. I think it's good for now (not perfect though). For now I approve, will see next work. Please ping me on regular basis. I'll try to review quicker.

2021-07-06 10:31 UTC, saas786 commented
> > I see, apologies, I missed the hidden comments in scroll.
> > Implemented changes, please review and let me know.
> 
> I see you fixed the most important things and also mentioned multiple times about phase 2. I think it's good for now (not perfect though). For now I approve, will see next work. Please ping me on regular basis. I'll try to review quicker.

Good, lets merge this PR, so I can rebase it onto phase2 branch.
And you can resume your review where you left off in newer PR.

Once this gets merged, I will right aware work on rebase, PR and will ping you to review again.

2021-07-06 12:08 UTC, pawelkmpt commented
> Good, lets merge this PR, so I can rebase it onto phase2 branch.

I can't merge it for some reason 🤔 

![Screenshot 2021-07-06 at 14 07 47](https://user-images.githubusercontent.com/5165721/124597296-95209080-de63-11eb-8857-abeae19fcf0b.png)

2021-07-06 14:59 UTC, saas786 commented
> 
> 
> > Good, lets merge this PR, so I can rebase it onto phase2 branch.
> 
> I can't merge it for some reason 🤔
> 
> ![Screenshot 2021-07-06 at 14 07 47](https://user-images.githubusercontent.com/5165721/124597296-95209080-de63-11eb-8857-abeae19fcf0b.png)

Hmmm its coding standard issues :(, can't skip it for this PR?

2021-07-08 05:36 UTC, pawelkmpt commented
I do not see such option. Also, who set these up?

2021-07-08 13:50 UTC, saas786 commented
> I do not see such option. Also, who set these up?

Hmmm, I think Leho did. Let me rebase this and we can close this PR, and we can review phase2 PR and I try to improve CS warnings.

2021-07-08 14:00 UTC, pawelkmpt commented
@lkraav suggested that... we can do it "old" way, on local machine and just push to main branch. are you able to do that?

2021-07-09 10:39 UTC, saas786 commented
> @lkraav suggested that... we can do it "old" way, on local machine and just push to main branch. are you able to do that?

I don't have permission on this repo. Please assign me appropriate permissions, so I can write to it directly, instead of sending PR via fork.

2021-07-09 10:47 UTC, merged