AutomateWoo ChartMogul integration base logic.
conversionxl/woocommerce-subscriptions-api-export pull request #28
Opened 2021-07-13 09:41 UTC by saas786

Test:

1) Setup workflows to test triggers, such as

a) Customer Created.
b) Order Created.
c) Order status changed.
d) Subscription created.
e) Subscription status changed.
f) Subscription cancelled.

2021-08-11 11:39 UTC, paulkirspuu requested changes
added a couple of comments.

overall looks good, no critical errors at first sight. if everything is tested, CXL coding standards applied, implementation QA'd by a second pair of eyes, and end result is as intended, id say its good to go.

2021-08-11 11:39 UTC, paulkirspuu commented on src/AutomateWoo/Actions/CustomerCreated.php
> +	/** @since 2021.06.29 */
comment alignment is off, for all similar files as well.

2021-08-11 11:39 UTC, paulkirspuu commented on src/AutomateWoo/Actions/CustomerCreated.php
> +	/**
description of method missing, same thing for all similar files.

2021-08-11 14:02 UTC, saas786 commented on src/AutomateWoo/Actions/CustomerCreated.php
> +	/**
@paulkirspuu
Take a look at both changes now...

2021-08-12 08:13 UTC, paulkirspuu commented on src/AutomateWoo/Actions/CustomerCreated.php
> +	/**
alright, all good on my end now, thanks!

2021-08-12 09:58 UTC, merged