Historical data, Rest API and improvements...
conversionxl/woocommerce-subscriptions-api-export pull request #35
Opened 2021-08-06 14:13 UTC by saas786

2021-08-12 09:49 UTC, pawelkmpt requested changes
1. @saas786 I reviewed REST API part and few other files. I did not review  AutomateWoo. I think @paulkirspuu would be a better person to do it.

2. In general it looks good. I left couple of comments in few files but once I opened next and next, I saw the same issues, so please apply changes to all API routes.

3. I see lot of repeated code across routes. Please think about refactoring.

4. WP core uses dashes in endpoints names, we usually use dashes as well, so let’s follow that and avoid making routes with underscore.

Eg. `data_sources` -> `data-sources`

2021-08-12 09:49 UTC, pawelkmpt commented on src/API/Routes/Orders.php
> +		}
Should be validated at param level. Please apply in all places

2021-08-12 09:49 UTC, pawelkmpt commented on src/API/Routes/Orders.php
> +		}
Doesn't specifying the integer type already check it?

2021-08-12 09:49 UTC, pawelkmpt commented on src/Schedulers/Actions/Customers.php
> +			// $date_query_after = $date->modify( $date_time_from )->format( 'Y-m-d' );
remove comments

2021-08-12 09:49 UTC, pawelkmpt commented on src/Schedulers/Actions/Customers.php
> +		*/
remove

2021-08-12 09:49 UTC, pawelkmpt commented on src/Schedulers/Actions/Customers.php
> +	}
can be dropped as it's identical as parent one

2021-08-12 09:49 UTC, pawelkmpt commented on src/Schedulers/Actions/Customers.php
> +	}
I think it can be dropped as it does not do anything different from parent

2021-08-12 09:49 UTC, pawelkmpt commented on src/Schedulers/Actions/Customers.php
> +		// $user = WPComponent::getUser( $user_id );
remove comment

2021-08-12 09:49 UTC, pawelkmpt commented on src/Schedulers/Actions/Orders.php
> +<?php
Applies to whole file: remove commented out code.

2021-08-12 09:49 UTC, pawelkmpt commented on src/Schedulers/Component.php
> +// use CXL\WC\ChartMogul\Schedulers\Actions\Orders as OrdersScheduler;
remove

2021-08-12 09:49 UTC, pawelkmpt commented on src/Schedulers/Contracts/SchedulerTraits.php
> +			'queue_batches' => 100,
put this value in constant so it's immediately visible on the top of the class

2021-08-12 09:49 UTC, pawelkmpt commented on src/Schedulers/Contracts/SchedulerTraits.php
> +		return $batch_sizes[ $action ] ?? 25;
put this value in constant so it's immediately visible on the top of the class

2021-08-12 09:49 UTC, pawelkmpt commented on src/WC/Subscriptions.php
> +			// $date_query_after = $date->modify( $date_time_from )->format( 'Y-m-d' );
remove

2021-08-12 10:06 UTC, pawelkmpt commented
@saas786 general issue: I see lot of inconsistency in code style. Part of the plugin uses `snake_case()` the other `camelCase()`. I'm looking at schedulers now and suddenly it's `snake_case()`.

2021-08-12 10:30 UTC, pawelkmpt requested changes

2021-08-12 10:30 UTC, pawelkmpt commented on src/Schedulers/Contracts/ExportScheduler.php
> +use CXL\WC\ChartMogul\Schedulers\Contracts\SchedulerTraits;
PHP Storm says it's unnecessary

2021-08-12 10:30 UTC, pawelkmpt commented on src/Schedulers/Contracts/ExportScheduler.php
> +	}
that's smart. I didn't know about it 👍

2021-08-12 10:30 UTC, pawelkmpt commented on src/Schedulers/Contracts/ExportScheduler.php
> +	{
opening bracket should be in the line above. apply this to all methods

2021-08-12 10:30 UTC, pawelkmpt commented on src/Schedulers/Contracts/ExportScheduler.php
> +			]
put such values as constants at the top of the class for immediate visibility

2021-08-12 10:30 UTC, pawelkmpt commented on src/Schedulers/Contracts/ExportScheduler.php
> +<?php
Add return types to methods in this class

2021-08-12 10:30 UTC, pawelkmpt commented on src/Schedulers/Contracts/SchedulerTraits.php
> +		$action_timestamp = time() + 5;
unused var

2021-08-12 17:26 UTC, saas786 commented on src/API/Routes/Customers.php
> +					],
> This could be tweaked with `minimum => 1`
> See: https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/#minimum-and-maximum

Please elaborate it.

2021-08-12 17:28 UTC, saas786 commented on src/API/Routes/Customers.php
> +						'validate_callback' => [ static::class, 'validateDataSource' ],
> Other callbacks use `self`. Please be consistent.
> 
> Also @lkraav prefers to use `static`. I don't remember why though.

Where specifically need to call current class, I am using `self`, in this case its being called from parent class, so using `static` thought can use `parent` but `static` takes care of `parent` and also `self` so prefer it.

2021-08-12 17:30 UTC, saas786 commented on src/API/Routes/DataSources.php
> +
> I see ping-pong block of code in multiple places. Could you extract it to some helper function?

have this refactor on mind, for this PR. Ignore it. As it can create lot of noise.

2021-08-13 07:58 UTC, pawelkmpt commented on src/API/Routes/Customers.php
> +					],
Customer ID has to be positive integer. I think there used to be `absint()` somewhere or condition checking if it's positive. Adding `minimum` make WP handle incorrect values which are `< 1`

2021-08-13 08:01 UTC, pawelkmpt commented on src/API/Routes/Customers.php
> +						'validate_callback' => [ static::class, 'validateDataSource' ],
What is the benefit with using different keywords for different cases? For me it's easier to follow one style and don't think about `self` vs `static`, but maybe there's something which makes your way better.

2021-08-13 08:09 UTC, pawelkmpt commented
@saas786 I see you made some changes. I resolved most of conversations but there are still few left + general comments.

2021-08-13 12:48 UTC, saas786 commented on src/API/Component.php
> +	public function boot() {
> `void` can be declared as return type

Ignore it, as Bootable is from Hybrid Core, so changing it breaks the code...

If ever or when possible, I will try to utilize Coding Standards on Hybrid Core and then we can update related code...

2021-08-13 12:49 UTC, saas786 commented on src/API/Contracts/Route.php
> +	const API_V1_NAMESPACE = 'cxl/chartmogul/v1';
Borrowed it from: https://github.com/Yoast/wordpress-seo/blob/0742e9b6ba4c0d6ae9d65223267a106b92a6a4a1/src/main.php#L32

So should be fine as is.

2021-08-13 13:02 UTC, saas786 commented on src/API/Routes/Customers.php
> +						'validate_callback' => [ static::class, 'validateDataSource' ],
> What is the benefit with using different keywords for different cases? For me it's easier to follow one style and don't think about `self` vs `static`, but maybe there's something which makes your way better.

I am not sure about the actual benefits of `self` vs `static`, but I like to use it like this. 
I use `static` initially and then have to refer current class, I replace it with `self`, same goes for `parent`.

2021-08-13 14:53 UTC, saas786 commented
@pawelkmpt 

Made some more changes. Please take a look.

I think its good for current PR, can work on remaining changes in next PR.

2021-08-16 08:30 UTC, pawelkmpt approved these changes

2021-08-16 08:31 UTC, merged