Tweak
conversionxl/woocommerce-subscriptions-api-export pull request #41
Opened 2021-08-19 15:38 UTC by saas786

- Upgraded Hybrid Core usage
- adding purchased order items name as tags in ChartMogul

2021-08-20 09:34 UTC, pawelkmpt commented
Hybrid Core is updated in https://github.com/saas786/cxl-common-lib/commit/fd63cce85a84fe35e72e881be9cfb5094728e2d6, right?

2021-08-20 09:34 UTC, pawelkmpt approved these changes

2021-08-20 09:57 UTC, saas786 commented
> Hybrid Core is updated in [saas786/cxl-common-lib@fd63cce](https://github.com/saas786/cxl-common-lib/commit/fd63cce85a84fe35e72e881be9cfb5094728e2d6), right?

Yes correct:
CXL Common Lib latest:
https://github.com/saas786/cxl-common-lib/releases/tag/v1.0.0-RC.1
https://github.com/saas786/cxl-common-lib/releases/download/v1.0.0-RC.1/cxl-common-lib.zip

2021-08-23 14:03 UTC, lkraav commented
@pawelkmpt is this OK to merge on staging?

I am looking into things and would like the latest tech available as the baseline.

2021-08-23 15:33 UTC, saas786 commented
> @pawelkmpt is this OK to merge on staging?
> 
> I am looking into things and would like the latest tech available as the baseline.

Yes from me, its latest. Pawel can take a look.

2021-08-24 08:36 UTC, lkraav commented
We don't need to self-host Sentry SDK, we're already using https://github.com/stayallive/wp-sentry

2021-08-24 09:19 UTC, pawelkmpt commented on src/Export/Component.php
> +		*/
@saas786 did you verify? can we remove the commented out code?

2021-08-24 09:23 UTC, pawelkmpt commented
> We don't need to self-host Sentry SDK, we're already using https://github.com/stayallive/wp-sentry

@saas786 can you confirm we have necessary dependencies and can drop the line from `composer.json`?

2021-08-24 11:02 UTC, saas786 commented on src/Export/Component.php
> +		*/
> @saas786 did you verify? can we remove the commented out code?

Did affect the logic, still in progress, most probably will remove.

2021-08-25 08:46 UTC, pawelkmpt approved these changes
@saas786 I approve, because I know it needs to be tested/go live, but please do following things in all future commits.

**1. Make more meaningful commit messages**

It's good you use semantic commit messages prefixes but it'd be better to know what `refactor` is about.

Please take a look at these:
* https://github.com/conversionxl/cxl-playbook-blocks/commits/main
* https://github.com/conversionxl/institute-plugin/commits/master

**2. Squash/amend commits if they're about same thing**

It's difficult to find and explain golden rule, so I'll use an example. These should be squashed:
* 97348c3af32ee1df15c555580edd00b91dd3dfed
* 49eb6b8cf0259599442c5e6939a8b768af9e2ee1

I mentioned recently it's better to have more smaller commits that one huge, but try to find the correct balance.

**3. Fix all coding standards warnings/errors**

It's difficult to read and review the code if every few lines is huge box with error.

2021-08-25 08:47 UTC, pawelkmpt commented
@saas786 let me know when it's ready to go live testing

2021-08-25 11:23 UTC, saas786 commented
> @saas786 let me know when it's ready to be merged and go live testing

Working out some change(s), if its in useable state, will use it in this PR, otherwise, will move it to next PR.

2021-08-31 14:01 UTC, saas786 commented
> > 1. Fix all coding standards warnings/errors
> 
> still an issue

Please take a look now, resolved 50% plus linting issues highlighted PHPCS test on GH.

2021-09-01 08:43 UTC, pawelkmpt requested changes
Use these for DB queries to fix remaining CS issues:

* `WordPress.DB.DirectDatabaseQuery.DirectQuery`
* `WordPress.DB.DirectDatabaseQuery.NoCaching`

> `Use of empty() is disallowed.`

I don't know where does it come from

2021-09-01 08:57 UTC, pawelkmpt commented on src/Tools/Logger/Component.php
> +use WP_Sentry_Version;
@saas786 did you test it?

2021-09-01 08:58 UTC, pawelkmpt commented on src/Tools/Logger/Component.php
> +	public static function get_logger(): MLogger {
Looking good, but I see one more thing to optimize. Every handler has the following line:

```php
$logger = new MLogger( gmdate( 'Y-m-d' ) . '.log' );
```

2021-09-01 10:38 UTC, pawelkmpt requested changes
`phpcs:ignore SlevomatCodingStandard.ControlStructures.DisallowEmpty.DisallowedEmpty` is placed in so many places that it should be:
* dropped from Slevomat,
* ignored with `phpcs:ignoreFile SlevomatCodingStandard.ControlStructures.DisallowEmpty.DisallowedEmpty`

2021-09-01 11:11 UTC, saas786 commented on src/Schedulers/Actions/Orders.php
> +			[ $order_id, , , , ,] = array_values( $action_data['get_args'] );
> wow, what does this do? I don't know this syntax

This article might explain it better: https://www.w3schools.com/php/func_array_list.asp

2021-09-01 12:39 UTC, saas786 commented
@pawelkmpt please review it now.

2021-09-01 14:44 UTC, merged