Tweaks
conversionxl/woocommerce-subscriptions-api-export pull request #43
Opened 2021-09-03 15:08 UTC by saas786

- refactor: renaming AutomateWoo action classes

2021-09-03 15:24 UTC, tomasced commented
I am thinking about this structure (like ASC):

```
$actions['cxl_cm_export_customer_new']               = Actions\ExportNewCustomer::class;
$actions['cxl_cm_export_order_new']                  = Actions\ExportNewOrder::class;
$actions['cxl_cm_export_order_status_update']        = Actions\ExportOrderStatusChange::class;
$actions['cxl_cm_export_subscription_new']           = Actions\ExportNewSubscription::class;
$actions['cxl_cm_export_subscription_status_update'] = Actions\ExportSubscriptionStatusChange::class;
$actions['cxl_cm_export_subscription_cancelled']     = Actions\ExportCancelledSubscription::class;
```

2021-09-07 11:58 UTC, pawelkmpt commented on src/CLI/Component.php
> +	 *
I mentioned long time ago that it'd be better to have regular commands for every action which is currently an assoc arg. Params are for passing necessary data, not triggering different commands and you keep adding them.

As far as I remember argument for keeping it as is was that refactor will be done in next phase. We get more and more code and the further we go, the more difficult it'll be to refactor.

I hope this is the last time you're adding command with using args.

2021-09-07 12:11 UTC, pawelkmpt requested changes

2021-09-07 12:11 UTC, pawelkmpt commented on src/WP/Component.php
> +
fix phpcs errors

2021-09-07 12:11 UTC, pawelkmpt commented on README.md
> +	 $ wp option add cxl_cm_export_exclude_email_domains "@cxl.com,@conversionxl.com,@conversionready.com" --autoload=no
it'd be better to use just domains and not require to put `@` upfront

2021-09-07 12:11 UTC, pawelkmpt commented on src/Export/Component.php
> +		$email          = null;
Why this is `null` instead of empty string?

2021-09-07 12:11 UTC, pawelkmpt commented on src/Export/Component.php
> +		}
I see this logic for the first time and it's smart once you understand it. Not so obvious at the first glance.

2021-09-07 12:11 UTC, pawelkmpt commented on src/Export/Component.php
> +				break;
add newline below to visually separate cases

2021-09-07 12:22 UTC, saas786 commented on src/Export/Component.php
> +		}
> I see this logic for the first time and it's smart once you understand it. Not so obvious at the first glance.

Other option is multiple if else, so avoided them. true will always execute switch statement and then case will handle the rest.

2021-09-07 12:24 UTC, saas786 commented on src/CLI/Component.php
> +	 *
> I mentioned long time ago that it'd be better to have regular commands for every action which is currently an assoc arg. Params are for passing necessary data, not triggering different commands and you keep adding them.
> 
> As far as I remember argument for keeping it as is was that refactor will be done in next phase. We get more and more code and the further we go, the more difficult it'll be to refactor.
> 
> I hope this is the last time you're adding command with using args.

`Export\Component.php` refactor is scheduled, because of amount of refactor, put it on hold for now.

2021-09-07 16:00 UTC, merged

2021-09-08 06:10 UTC, pawelkmpt commented on src/Export/Component.php
> +		}
Yes, I noticed. I like the switch way 👍